#put vallue 1.0 - 0.00000000001
Droppercent:
  Mobs:
    CAT: 0.02
    creeper: 0.005
    zombie: 0.002
    skeleton: 0.002
    wither_skeleton: 0.025
    spider: 0.002
    enderman: 0.002
    blaze: 0.002
    horse: 0.02
    donkey: 0.02
    squid: 0.05
    silverfish: 0.005
    enderdragon: 0.05
    slime: 0.01
    iron_golem: 0.005
    mushroom_cow: 0.02
    bat: 0.005
    zombified_piglin: 0.002
    snowman: 0.02
    ghast: 0.005
    pig: 0.02
    sheep: 0.02
    cow: 0.02
    chicken: 0.02
    ocelot: 0.05
    witch: 0.005
    magma_cube: 0.001
    wolf: 0.02
    cave_spider: 0.002
    rabbit: 0.002
    guardian: 0.025
    elder_guardian: 0.030
    polar_bear: 0.005
    shulker: 0.02
    stray: 0.005
    endermite: 0.002
    evoker: 0.005
    illusioner: 0.005
    vindicator: 0.005
    wither: 0.005
    vex: 0.004
    llama: 0.08
    parrot: 0.08
    husk: 0.002
    zombie_villager: 0.5
    skeleton_horse: 0.002
    zombie_horse: 0.002
    mule: 0.002
    turtle: 0.002
    phantom: 0.001
    cod: 0.002
    salmon: 0.002
    pufferfish: 0.002
    tropical_fish: 0.002
    drowned: 0.002
    dolphin: 0.002
    #new added mobs
    villager: 0.5
    bee: 0.02
    fox: 0.02
    hoglin: 0.005
    panda: 0.02
    piglin: 0.002
    piglin_brute: 0.005
    pillager: 0.005
    ravager: 0.005
    snow_golem: 0.02
    strider: 0.02
    trader_llama: 0.002
    wandering_trader: 0.5
    zoglin: 0.005



